### ISSUE TITLE
Can't sign in after creating account

### ISSUE THREAD

**Issue by mribbons** [kafkas/coronamap#2]
After signing up a few errors occur. 

I tried swiping left and signing in, but the sign in button just spins for a second then nothing.

When I restart the app it seems to try to log back in with the same credentials and the same errors occur.

[Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'wellbeing.toString')]

Stack trace:
  http://192.168.75.69:19007/src%5CRoot.tsx.bundle?platform=android&dev=true&minify=false&hot=false:200232:103 in downloadUserInfoToLocalDB$
  node_modules\regenerator-runtime\runtime.js:45:44 in tryCatch
  node_modules\regenerator-runtime\runtime.js:274:30 in invoke
  node_modules\regenerator-runtime\runtime.js:45:44 in tryCatch
  node_modules\regenerator-runtime\runtime.js:135:28 in invoke
  node_modules\regenerator-runtime\runtime.js:145:19 in PromiseImpl.resolve.then$argument_0
  node_modules\promise\setimmediate\core.js:37:14 in tryCallOne
  node_modules\promise\setimmediate\core.js:123:25 in setImmediate$argument_0
  node_modules\react-native\Libraries\Core\Timers\JSTimers.js:146:14 in _callTimer
  node_modules\react-native\Libraries\Core\Timers\JSTimers.js:194:17 in _callImmediatesPass
  node_modules\react-native\Libraries\Core\Timers\JSTimers.js:458:30 in callImmediates
  [native code]:null in callImmediates
  node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:407:6 in __callImmediates
  node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:143:6 in __guard$argument_0
  node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:384:10 in __guard
  node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:142:17 in __guard$argument_0
  [native code]:null in flushedQueue
  [native code]:null in callFunctionReturnFlushedQueue

**Comment by jtich** [comment]
I'm experiencing the same issue. Do we know what `wellbeing` is used for?

**Comment by HelioStrike** [comment]
@mribbons @jtich @kafkas The values of the `wellbeing` are defined [here](https://github.com/kafkas/coronamap/blob/master/src/data-types/Wellbeing.ts). When the user is being created, the value of the `wellbeing` isn't being set in the firebase doc, causing the it to be undefined and throwing the error. How should we go about solving this? We could either handle the `undefined` with an `if` statement, or we could update the user's document during sign up.

**Comment by kafkas** [comment]
@HelioStrike Great catch! The way it's currently arranged, if statement would be the right way. Could you please also make `lastLocation` and `wellbeing` optional in `FirestoreUserDoc`. That's the source of confusion.

**Comment by kafkas** [comment]
Nailed by @HelioStrike
