### ISSUE TITLE
Firebase: Firebase App named '[DEFAULT]' already exists

### ISSUE THREAD

**Issue by mribbons** [kafkas/coronamap#3]
Firebase: Firebase App named '[DEFAULT]' already exists (app/duplicate-app).
* http://192.168.75.69:19007/src%5CRoot.tsx.bundle?platform=android&dev=true&minify=false&hot=false:132224:30 in FirebaseError
* http://192.168.75.69:19007/src%5CRoot.tsx.bundle?platform=android&dev=true&minify=false&hot=false:132259:36 in create
- node_modules\@firebase\app\dist\index.rn.cjs.js:354:5 in createFirebaseNamespaceCore
* src\api\index.ts:6:29 in initialize
* src\actions\auth\updatePassword.ts:37:59 in <anonymous>

**Comment by kafkas** [comment]
Fixed by @HelioStrike
